### ISSUE TITLE
Error with Watchdog on windows

### ISSUE THREAD

**Issue by ajpen** [pycco-docs/pycco#86]
While in the same directory as main.py I ran this command to enable regeneration: pycco -w main.py
Note that in the same dir, pycco -w main.py works perfectly and watchdog is currently installed.

However this was returned:

pycco = main.py -> docs\main.html
Traceback (most recent call last):
  File "C:\Python27\Scripts\pycco-script.py", line 9, in <module>
    load_entry_point('Pycco==0.3.0', 'console_scripts', 'pycco')()
  File "C:\Python27\lib\site-packages\pycco\main.py", line 492, in main
    monitor(sources, opts)
  File "C:\Python27\lib\site-packages\pycco\main.py", line 456, in monitor
    observer.start()
  File "C:\Python27\lib\site-packages\watchdog\observers\api.py", line 255, in s
tart
    emitter.start()
  File "C:\Python27\lib\site-packages\watchdog\utils\__init__.py", line 111, in
start
    self.on_thread_start()
  File "C:\Python27\lib\site-packages\watchdog\observers\read_directory_changes.
py", line 70, in on_thread_start
    self._handle = get_directory_handle(self.watch.path)
  File "C:\Python27\lib\site-packages\watchdog\observers\winapi.py", line 278, i
n get_directory_handle
    None, OPEN_EXISTING, WATCHDOG_FILE_FLAGS, None)
  File "C:\Python27\lib\site-packages\watchdog\observers\winapi.py", line 116, i
n _errcheck_handle
    raise ctypes.WinError()
WindowsError: [Error 3] The system cannot find the path specified.

**Comment by goosemo** [comment]
Could you clarify this ticket please? Are you saying that this works:


```
$ pycco -w main.py
```

And this does not, in windows:

```
$ pycco -w docs\main.py
```

Please give examples of your run in the ticket, formatted as code, and include the console tool you're using as well as the version of windows and pycco you're using, as this will greatly aide our ability to patch the code properly and quickly.
